# Generated by Django 2.0.5 on 2018-06-03 12:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_amount', models.IntegerField(default=0, verbose_name='token数')),
                ('transition_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='投票编号')),
                ('trans_status', models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '上链中')], default='paying', max_length=30, verbose_name='交易状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Proposals', verbose_name='提案')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易信息',
                'verbose_name_plural': '交易信息',
            },
        ),
        migrations.CreateModel(
            name='UserProposalOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_amount', models.IntegerField(default=0, verbose_name='token数')),
                ('transition_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='投票编号')),
                ('trans_status', models.CharField(choices=[('TRADE_SUCCESS', '成功'), ('TRADE_CLOSED', '超时关闭'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束'), ('paying', '上链中')], default='paying', max_length=30, verbose_name='交易状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('proposal_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ProposalOptions', verbose_name='提案')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易信息',
                'verbose_name_plural': '交易信息',
            },
        ),
    ]
