# Generated by Django 2.0.5 on 2018-06-03 12:26

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='热搜词')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '热搜排行',
                'verbose_name_plural': '热搜排行',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '首页提案',
                'verbose_name_plural': '首页提案',
            },
        ),
        migrations.CreateModel(
            name='ProposalOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='选项')),
                ('desc', models.TextField(default='', help_text='品牌描述', max_length=200, verbose_name='选项描述')),
                ('token_received', models.IntegerField(default=0, verbose_name='票数')),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '投票选项',
                'verbose_name_plural': '投票选项',
            },
        ),
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_sn', models.CharField(default='', max_length=50, verbose_name='提案唯一编码（标准待定）')),
                ('name', models.CharField(max_length=100, verbose_name='提案名')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('proposals_brief', models.TextField(max_length=500, verbose_name='投票简短描述')),
                ('proposals_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总票据数(B)')),
                ('balance_tokens', models.IntegerField(default=0, verbose_name='可售票据数(B)')),
                ('token_price', models.IntegerField(default=0, verbose_name='票据价格(B)')),
                ('token_received', models.IntegerField(default=0, verbose_name='收到总投票数')),
                ('proposal_front_image', models.ImageField(blank=True, null=True, upload_to='proposals/images/', verbose_name='封面图')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新发起')),
                ('is_hot', models.BooleanField(default=False, help_text='是否高关注', verbose_name='是否高关注')),
                ('is_anonymous', models.BooleanField(default=False, help_text='是否匿名', verbose_name='是否匿名')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='ProposalsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='proposals.ProposalsCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '提案类别',
                'verbose_name_plural': '提案类别',
            },
        ),
        migrations.CreateModel(
            name='ProposalsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='品牌名', max_length=30, verbose_name='提案品牌名')),
                ('desc', models.TextField(default='', help_text='品牌描述', max_length=200, verbose_name='品牌描述')),
                ('image', models.ImageField(max_length=200, upload_to='brands/')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='proposals.ProposalsCategory', verbose_name='投票类目')),
            ],
            options={
                'verbose_name': '提案品牌',
                'verbose_name_plural': '提案品牌',
                'db_table': 'proposals_proposalsbrand',
            },
        ),
        migrations.CreateModel(
            name='ProposalsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('proposals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proposals.Proposals', verbose_name='商品')),
            ],
            options={
                'verbose_name': '投票轮播',
                'verbose_name_plural': '投票轮播',
            },
        ),
        migrations.AddField(
            model_name='proposals',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ProposalsCategory', verbose_name='商品类目'),
        ),
        migrations.AddField(
            model_name='proposaloptions',
            name='proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='proposals.Proposals', verbose_name='投票选项'),
        ),
        migrations.AddField(
            model_name='indexad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='proposals.ProposalsCategory', verbose_name='商品类目'),
        ),
        migrations.AddField(
            model_name='indexad',
            name='proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='proposals.Proposals'),
        ),
        migrations.AddField(
            model_name='banner',
            name='proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Proposals', verbose_name='商品'),
        ),
    ]
