# Generated by Django 2.0.5 on 2018-06-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexad',
            options={'verbose_name': '提案广告', 'verbose_name_plural': '提案广告'},
        ),
        migrations.AlterModelOptions(
            name='proposals',
            options={'verbose_name': '提案信息', 'verbose_name_plural': '提案信息'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.Proposals', verbose_name='提案'),
        ),
        migrations.AlterField(
            model_name='indexad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='proposals.ProposalsCategory', verbose_name='提案类型'),
        ),
        migrations.AlterField(
            model_name='proposaloptions',
            name='desc',
            field=models.TextField(default='', help_text='选项描述', max_length=200, verbose_name='选项描述'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ProposalsCategory', verbose_name='提案类型'),
        ),
        migrations.AlterField(
            model_name='proposalsimage',
            name='proposals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='proposals.Proposals', verbose_name='提案'),
        ),
    ]
