# Generated by Django 2.0.5 on 2018-06-06 16:33

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20180605_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposals',
            name='proposals_brief',
        ),
        migrations.RemoveField(
            model_name='proposals',
            name='proposals_desc',
        ),
        migrations.AddField(
            model_name='proposals',
            name='brief',
            field=models.TextField(default='', help_text='简述', max_length=500, verbose_name='投票简短描述'),
        ),
        migrations.AddField(
            model_name='proposals',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', help_text='内容详情', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='balance_tokens',
            field=models.IntegerField(default=0, help_text='可售票据数', verbose_name='可售票据数(B)'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='category',
            field=models.ForeignKey(help_text='提案类别', on_delete=django.db.models.deletion.CASCADE, to='proposals.ProposalsCategory', verbose_name='提案类型'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='click_num',
            field=models.IntegerField(default=0, help_text='点击数量', verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='结束时间', verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='fav_num',
            field=models.IntegerField(default=0, help_text='关注数', verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='is_new',
            field=models.BooleanField(default=False, help_text='是否新发起', verbose_name='是否新发起'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='name',
            field=models.CharField(help_text='标题', max_length=100, verbose_name='提案名'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='proposal_front_image',
            field=models.ImageField(blank=True, help_text='封面', null=True, upload_to='proposals/images/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='proposal_sn',
            field=models.CharField(default='', help_text='提案编码', max_length=50, verbose_name='提案唯一编码（标准待定）'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='发起时间', verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='token_price',
            field=models.IntegerField(default=0, help_text='票据价格', verbose_name='票据价格(B)'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='token_received',
            field=models.IntegerField(default=0, help_text='收到总票数', verbose_name='收到总投票数'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='总票据数', verbose_name='总票据数(B)'),
        ),
        migrations.AlterField(
            model_name='proposalscategory',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='创建时间', verbose_name='添加时间'),
        ),
    ]
