# Generated by Django 2.0.5 on 2018-06-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20180606_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersponsorproposals',
            options={'verbose_name': '用户发起投票', 'verbose_name_plural': '用户发起投票'},
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(default='', help_text='详细地址', max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='userproposaloption',
            name='proposal_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ProposalOptions', verbose_name='投票选项'),
        ),
    ]
