# Generated by Django 2.0.5 on 2018-06-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20180606_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(blank=True, help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(default='', help_text='标题', max_length=100, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='userproposals',
            name='proposal',
            field=models.ForeignKey(help_text='提案id', on_delete=django.db.models.deletion.CASCADE, to='proposals.Proposals', verbose_name='提案'),
        ),
        migrations.AlterField(
            model_name='userproposals',
            name='token_amount',
            field=models.IntegerField(default=0, help_text='票据数量（投票权重）', verbose_name='token数'),
        ),
    ]
